package com.enums;

public enum Achievement {
    UNLOCKCOSTUMES,
    PARTICIPATION_PRACTICE,
    PARTICIPATION_GAME,
    NUMGAMES_FIVE,
    NUMGAMES_TEN,
    NUMGAMES_TWENTY,
    NUMGAMES_FIFTY,
    NUMGAMES_HUNDRED,
    HIGHSCORE_SEVENTYFIVE,
    HIGHSCORE_NINETY,
    HIGHSCORE_HUNDRED,
    TIMER_FORTY,
    TIMER_THIRTY,
    TIMER_FIFTEEN,
    STAR_FIVE,
    STAR_TWENTYFIVE,
    STAR_SEVENTY,
    STAR_HUNDRED
}
